application:
  external:
    backends:
      inventory-service:
        base-url: https://inventory-service
      payment-service:
        base-url: https://payment-service.payments.svc.cluster.local

spring:
  application:
    name: order-service
